### ISSUE TITLE
Demo pages asks for password

### ISSUE THREAD

**Issue by wondie** [davicustodio/Leaflet.StyledLayerControl#10]
When I visit the demo pages, both ask for password in chrome and firefox.

**Comment by davicustodio** [comment]
the problem was with the remote call to https://gist.github.com/crofty/2197042 plugin that implements access to google maps in the Leaflet.
I copied the plugin to the repository to become independent remote access.
The change is in that commit:https://github.com/davicustodio/Leaflet.StyledLayerControl/commit/67f7abdd41fa841eeb07db172665b9665cc15640

Now you can open the demo without the authentication request.

**Comment by wondie** [comment]
It works now. Thank you!
