### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by neothemachine** [davicustodio/Leaflet.StyledLayerControl#8]
```
TypeError: L.Google is not a constructor

var g_roadmap   = new L.Google('ROADMAP');
```

**Comment by davicustodio** [comment]
Please make sure your html is the call the apis Google Maps:

<script src = "http://maps.google.com/maps/api/js?v=3.2&sensor=false"> </ script>
<script src = "http://matchingnotes.com/javascripts/leaflet-google.js"> </ script>

... If you already are there, make sure they are being charged using any developer tool to monitor calls http.

.. Make me know the result

**Comment by davicustodio** [comment]
Please make sure your html is the call the apis Google Maps:

<script src = "http://maps.google.com/maps/api/js?v=3.2&sensor=false"> </ script>
<script src = "http://matchingnotes.com/javascripts/leaflet-google.js"> </ script>

... If you already are there, make sure they are being charged using any developer tool to monitor calls http.

.. Make me know the result

**Comment by davicustodio** [comment]
Please make sure your html is the call the apis Google Maps:

``` 
<script src = "http://maps.google.com/maps/api/js?v=3.2&sensor=false"> </ script>"
<script src = "http://matchingnotes.com/javascripts/leaflet-google.js"> </ script>
```

... If you already are there, make sure they are being charged using any developer tool to monitor calls http.

.. Make me know the result

**Comment by neothemachine** [comment]
Sorry, I meant that the live demos you supply are broken:
http://davicustodio.github.io/Leaflet.StyledLayerControl/examples/example1.html
Which is still broken.

**Comment by davicustodio** [comment]
the problem was with the remote call to
https://gist.github.com/crofty/2197042 plugin that implements access to
google maps in the Leaflet.
I copied the plugin to the repository to become independent remote access.
The change is in that commit:
https://github.com/davicustodio/Leaflet.StyledLayerControl/commit/67f7abdd41fa841eeb07db172665b9665cc15640

Now you can open the demo without the authentication request.

On Wed, Sep 23, 2015 at 4:32 AM, Maik Riechert <notifications@github.com>
wrote:

> Sorry, I meant that the live demos you supply are broken:
>
> http://davicustodio.github.io/Leaflet.StyledLayerControl/examples/example1.html
> Which is still broken.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davicustodio/Leaflet.StyledLayerControl/issues/8#issuecomment-142519496>
> .
>



-- 
Davi de O. Custódio

**Comment by neothemachine** [comment]
Perfect, thanks.
